-- ============================================================
-- RobChat Multi-Tenant Schema
-- PostgreSQL Migration #001
-- ============================================================
-- Run: psql -U robchat -d robchat -f 001_initial_schema.sql
-- ============================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. TENANTS — one row per customer (replaces config.php)
-- ---------------------------------------------------------------------------
CREATE TABLE tenants (
    id              TEXT PRIMARY KEY,                    -- short slug used in embed: data-robchat-id="acme"
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Auth (dashboard login)
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,                       -- bcrypt via password_hash()
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,

    -- Branding (sent to widget via tenant-config API)
    display_name    TEXT NOT NULL,                       -- "Acme AI Assistant"
    greeting        TEXT NOT NULL DEFAULT 'Hey! How can I help you today?',
    accent_color    TEXT NOT NULL DEFAULT '#FF4D2E',
    accent_gradient TEXT DEFAULT 'linear-gradient(135deg, #FF4D2E, #C850C0)',
    ai_accent       TEXT DEFAULT '#8B5CF6',
    widget_position TEXT NOT NULL DEFAULT 'bottom-right' CHECK (widget_position IN ('bottom-right', 'bottom-left')),
    quick_replies   JSONB DEFAULT '[]'::jsonb,           -- ["What services?", "Pricing", "Book a call"]

    -- LLM configuration
    system_prompt   TEXT NOT NULL DEFAULT '',
    primary_llm     TEXT NOT NULL DEFAULT 'openai' CHECK (primary_llm IN ('openai', 'anthropic')),
    openai_api_key  TEXT,                                -- encrypted at rest (app-level)
    anthropic_api_key TEXT,                              -- encrypted at rest (app-level)
    openai_model    TEXT NOT NULL DEFAULT 'gpt-4o',
    anthropic_model TEXT NOT NULL DEFAULT 'claude-sonnet-4-20250514',
    max_tokens      INTEGER NOT NULL DEFAULT 500,

    -- Lead capture
    lead_email      TEXT,                                -- where lead notifications get sent
    lead_webhook    TEXT,                                -- optional webhook URL for lead events

    -- Calendar (optional)
    calendar_enabled        BOOLEAN NOT NULL DEFAULT FALSE,
    google_service_account  JSONB,                       -- service account JSON blob
    google_calendar_id      TEXT,
    booking_duration_min    INTEGER DEFAULT 30,
    booking_timezone        TEXT DEFAULT 'America/Chicago',
    booking_hours_start     INTEGER DEFAULT 9,
    booking_hours_end       INTEGER DEFAULT 17,
    booking_days            JSONB DEFAULT '[1,2,3,4,5]'::jsonb,

    -- Rate limiting
    rate_limit_per_minute   INTEGER NOT NULL DEFAULT 10,
    rate_limit_per_hour     INTEGER NOT NULL DEFAULT 60,
    max_conversation_length INTEGER NOT NULL DEFAULT 50,

    -- Allowed origins (CORS)
    allowed_origins JSONB DEFAULT '[]'::jsonb            -- ["https://acme.com", "https://www.acme.com"]
);

-- ---------------------------------------------------------------------------
-- 2. SESSIONS — chat sessions scoped to a tenant
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
    id              TEXT PRIMARY KEY,                    -- UUID generated by widget
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    page_url        TEXT,
    user_agent      TEXT,
    ip_hash         TEXT,
    lead_captured   BOOLEAN NOT NULL DEFAULT FALSE,
    message_count   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_sessions_tenant ON sessions(tenant_id);
CREATE INDEX idx_sessions_tenant_active ON sessions(tenant_id, last_active DESC);

-- ---------------------------------------------------------------------------
-- 3. MESSAGES — conversation messages
-- ---------------------------------------------------------------------------
CREATE TABLE messages (
    id              SERIAL PRIMARY KEY,
    session_id      TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT NOT NULL,
    tokens_used     INTEGER DEFAULT 0,
    llm_provider    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_session ON messages(session_id);
CREATE INDEX idx_messages_session_time ON messages(session_id, created_at);

-- ---------------------------------------------------------------------------
-- 4. LEADS — captured contact info
-- ---------------------------------------------------------------------------
CREATE TABLE leads (
    id              SERIAL PRIMARY KEY,
    session_id      TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name            TEXT,
    email           TEXT,
    company         TEXT,
    phone           TEXT,
    project_type    TEXT,
    budget          TEXT,
    message         TEXT,
    source_page     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    email_sent      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_leads_tenant ON leads(tenant_id);
CREATE INDEX idx_leads_tenant_time ON leads(tenant_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- 5. RATE LIMITS — per-tenant, per-IP throttling
-- ---------------------------------------------------------------------------
CREATE TABLE rate_limits (
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    ip_hash         TEXT NOT NULL,
    window_type     TEXT NOT NULL,                       -- 'minute' or 'hour'
    count           INTEGER NOT NULL DEFAULT 1,
    expires_at      TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (tenant_id, ip_hash, window_type)
);

CREATE INDEX idx_rate_limits_expires ON rate_limits(expires_at);

-- ---------------------------------------------------------------------------
-- 6. HELPER: auto-update updated_at on tenants
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tenants_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- 7. SEED: demo tenant for local development
-- ---------------------------------------------------------------------------
INSERT INTO tenants (id, email, password_hash, display_name, greeting, system_prompt, quick_replies, allowed_origins)
VALUES (
    'demo_001',
    'demo@robchat.dev',
    -- password: "password" — run `php backend/setup.php` to generate a new hash
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
    'Acme AI Assistant',
    'Hey! I''m Acme''s AI assistant. Ask me anything about our services, or tell me about your project.',
    'You are a helpful AI assistant for Acme Web Solutions. You help visitors learn about web design, development, and SEO services. You qualify leads by asking about their project needs, timeline, and budget.',
    '["What services do you offer?", "How much does a website cost?", "Book a consultation"]'::jsonb,
    '["http://localhost:4321", "http://localhost:3000", "http://127.0.0.1:5500"]'::jsonb
);

COMMIT;
