-- Migration 014: Superuser Role Support
-- Run with: psql -U hwchat -d hwchat -f migrations/014_superuser_role.sql
-- Then restart PHP: systemctl restart ea-php82-php-fpm ea-php83-php-fpm

-- 1. Add role column to tenants table
ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'tenant_admin'
    CHECK (role IN ('superadmin', 'tenant_admin'));

-- 2. Create superadmin account
-- Password: HWSuper2026! (change after first login)
-- The password hash below is generated by PHP's password_hash('HWSuper2026!', PASSWORD_BCRYPT)
-- You MUST generate the real hash on the server. Run this on the server:
--   php -r "echo password_hash('HWSuper2026!', PASSWORD_BCRYPT);"
-- Then replace the placeholder below with the output.

INSERT INTO tenants (
    id, email, password_hash, display_name, role,
    system_prompt, community_type, is_active
) VALUES (
    'hw_superadmin',
    'admin@hillwoodcommunities.com',
    '$2y$10$5Q1lyXY/iNtC.FHCrWbTt.no8cwjdc/gd9YouzGKeSPa7bl3Rp/2a',  -- REPLACE with output of: php -r "echo password_hash('HWSuper2026!', PASSWORD_BCRYPT);"
    'Hillwood Admin',
    'superadmin',
    '',
    'parent',
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    role = 'superadmin',
    display_name = 'Hillwood Admin';

-- 3. Ensure existing tenants are explicitly tenant_admin
UPDATE tenants SET role = 'tenant_admin' WHERE role IS NULL OR role = '';

-- 4. Add global_settings entries for community directory (future use)
INSERT INTO global_settings (key, value)
VALUES ('community_directory', '{}')
ON CONFLICT (key) DO NOTHING;
